// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3m7CDUOVyJ2jOAsoRsp909ETlpwBln8w',
    appId: '1:102665853076:web:4ff207a4c50274051ffc81',
    messagingSenderId: '102665853076',
    projectId: 'taskflow-c145c',
    authDomain: 'taskflow-c145c.firebaseapp.com',
    storageBucket: 'taskflow-c145c.appspot.com',
    measurementId: 'G-TPBKBHXYP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSjn35cGtvpd2QS93f_IxBeN7zB4-ov4',
    appId: '1:102665853076:android:731a0b5fc128cc701ffc81',
    messagingSenderId: '102665853076',
    projectId: 'taskflow-c145c',
    storageBucket: 'taskflow-c145c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TRHBtDcLJi9FLWjRvsqcZ9tC40eNoec',
    appId: '1:102665853076:ios:d6c52438d11176341ffc81',
    messagingSenderId: '102665853076',
    projectId: 'taskflow-c145c',
    storageBucket: 'taskflow-c145c.appspot.com',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TRHBtDcLJi9FLWjRvsqcZ9tC40eNoec',
    appId: '1:102665853076:ios:d6c52438d11176341ffc81',
    messagingSenderId: '102665853076',
    projectId: 'taskflow-c145c',
    storageBucket: 'taskflow-c145c.appspot.com',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3m7CDUOVyJ2jOAsoRsp909ETlpwBln8w',
    appId: '1:102665853076:web:a3783819c5dea33c1ffc81',
    messagingSenderId: '102665853076',
    projectId: 'taskflow-c145c',
    authDomain: 'taskflow-c145c.firebaseapp.com',
    storageBucket: 'taskflow-c145c.appspot.com',
    measurementId: 'G-RF8L17DCLM',
  );
}
